In [41]:
import pandas as pd
import os
DATAPATH = 'C:\\anal_danych\\Labs\\swps-metody-analizy-danych\\lab_05\\data'
df = pd.read_csv(os.path.join(DATAPATH, 'loan_data.csv'))

1. Zamień nazwę kolumny `loan_amnt` na `loan_amount`.

In [42]:
df.rename(columns={'loan_amnt': 'loan_amount'}, inplace=True)
df.columns

Index(['person_age', 'person_gender', 'person_education', 'person_income',
       'person_emp_exp', 'person_home_ownership', 'loan_amount', 'loan_intent',
       'loan_int_rate', 'loan_percent_income', 'cb_person_cred_hist_length',
       'credit_score', 'previous_loan_defaults_on_file', 'loan_status'],
      dtype='object')

2. Z ramki danych wykorzystanej w przykładach (loan) wyświetl:
* a) tylko kolumny 'person_gender', 'person_age' oraz 'person_income',
* b) wiersze od 1000 do 2000 włącznie (chodzi o kolejne wiersze w ramce, a nie wartość indeksu),
* c) wiersze parzyste,
* d) wiersze o parzystej wartości w kolumnie indeks,
* e) pierwszą i ostatnią kolumnę.

In [ ]:
#a)
# df['person_gender']
# df['person_age']
# df['person_income']

# col_names = list(df.columns)
# result = col_names[1:2] + col_names[0:1] + col_names[3:4]
# print(result) #['person_gender', 'person_age', 'person_income']
# a = df.loc[:,result]
# a.head()

#df.iloc[:, [1,0,3]]

      person_gender  person_age  person_income
0            female        22.0        71948.0
1            female        21.0        12282.0
2            female        25.0        12438.0
3            female        23.0        79753.0
4              male        24.0        66135.0
...             ...         ...            ...
44995          male        27.0        47971.0
44996        female        37.0        65800.0
44997          male        33.0        56942.0
44998          male        29.0        33164.0
44999          male        24.0        51609.0

[45000 rows x 3 columns]

In [45]:
#b)
df.iloc[1000:2001]

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amount,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
1000,23.0,male,Bachelor,30059.0,0,MORTGAGE,1375.0,MEDICAL,11.11,0.05,4.0,506,No,1
1001,24.0,male,Bachelor,68258.0,2,RENT,18000.0,EDUCATION,13.48,0.26,3.0,671,No,1
1002,21.0,male,Bachelor,60821.0,0,RENT,18000.0,EDUCATION,14.74,0.30,2.0,530,No,1
1003,25.0,male,High School,70432.0,6,RENT,18000.0,VENTURE,11.01,0.26,4.0,609,No,1
1004,21.0,female,Bachelor,63842.0,0,RENT,18000.0,MEDICAL,19.69,0.28,2.0,678,No,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1996,21.0,male,Master,37264.0,0,RENT,14000.0,MEDICAL,10.65,0.38,2.0,545,No,1
1997,24.0,female,Associate,36841.0,4,RENT,14000.0,DEBTCONSOLIDATION,7.90,0.38,2.0,538,No,1
1998,24.0,male,Bachelor,37068.0,2,MORTGAGE,3075.0,DEBTCONSOLIDATION,11.01,0.08,4.0,521,Yes,0
1999,22.0,male,Bachelor,37513.0,0,RENT,14000.0,VENTURE,6.99,0.37,4.0,595,No,1
2000,23.0,female,Associate,36711.0,0,RENT,14000.0,MEDICAL,11.26,0.38,3.0,554,No,1

In [51]:
#c)wiersze parzyste
print(df.index)
df.iloc[::2]

RangeIndex(start=0, stop=45000, step=1)

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amount,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
0,22.0,female,Master,71948.0,0,RENT,35000.0,PERSONAL,16.02,0.49,3.0,561,No,1
2,25.0,female,High School,12438.0,3,MORTGAGE,5500.0,MEDICAL,12.87,0.44,3.0,635,No,1
4,24.0,male,Master,66135.0,1,RENT,35000.0,MEDICAL,14.27,0.53,4.0,586,No,1
6,26.0,female,Bachelor,93471.0,1,RENT,35000.0,EDUCATION,12.42,0.37,3.0,701,No,1
8,24.0,female,Associate,100684.0,3,RENT,35000.0,PERSONAL,8.90,0.35,2.0,544,No,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44990,31.0,male,Master,136832.0,9,RENT,12319.0,PERSONAL,16.92,0.09,7.0,722,No,1
44992,23.0,female,Bachelor,40925.0,0,RENT,9000.0,PERSONAL,11.01,0.22,4.0,487,No,1
44994,24.0,female,Associate,31924.0,2,RENT,12229.0,MEDICAL,10.70,0.38,4.0,678,No,1
44996,37.0,female,Associate,65800.0,17,RENT,9000.0,HOMEIMPROVEMENT,14.07,0.14,11.0,621,No,1
44998,29.0,male,Bachelor,33164.0,4,RENT,12000.0,EDUCATION,13.23,0.36,6.0,604,No,1

In [52]:
#d)wiersze o parzystej wartości w kolumnie indeks
df.loc[df.index %2 == 0]

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amount,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
0,22.0,female,Master,71948.0,0,RENT,35000.0,PERSONAL,16.02,0.49,3.0,561,No,1
2,25.0,female,High School,12438.0,3,MORTGAGE,5500.0,MEDICAL,12.87,0.44,3.0,635,No,1
4,24.0,male,Master,66135.0,1,RENT,35000.0,MEDICAL,14.27,0.53,4.0,586,No,1
6,26.0,female,Bachelor,93471.0,1,RENT,35000.0,EDUCATION,12.42,0.37,3.0,701,No,1
8,24.0,female,Associate,100684.0,3,RENT,35000.0,PERSONAL,8.90,0.35,2.0,544,No,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44990,31.0,male,Master,136832.0,9,RENT,12319.0,PERSONAL,16.92,0.09,7.0,722,No,1
44992,23.0,female,Bachelor,40925.0,0,RENT,9000.0,PERSONAL,11.01,0.22,4.0,487,No,1
44994,24.0,female,Associate,31924.0,2,RENT,12229.0,MEDICAL,10.70,0.38,4.0,678,No,1
44996,37.0,female,Associate,65800.0,17,RENT,9000.0,HOMEIMPROVEMENT,14.07,0.14,11.0,621,No,1
44998,29.0,male,Bachelor,33164.0,4,RENT,12000.0,EDUCATION,13.23,0.36,6.0,604,No,1

In [57]:
#e) pierwszą i ostatnią kolumnę.
df.iloc[:,[0,-1]]

       person_age  loan_status
0            22.0            1
1            21.0            0
2            25.0            1
3            23.0            1
4            24.0            1
...           ...          ...
44995        27.0            1
44996        37.0            1
44997        33.0            1
44998        29.0            1
44999        24.0            1

[45000 rows x 2 columns]

In [61]:
df

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amount,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
0,22.0,female,Master,71948.0,0,RENT,35000.0,PERSONAL,16.02,0.49,3.0,561,No,1
1,21.0,female,High School,12282.0,0,OWN,1000.0,EDUCATION,11.14,0.08,2.0,504,Yes,0
2,25.0,female,High School,12438.0,3,MORTGAGE,5500.0,MEDICAL,12.87,0.44,3.0,635,No,1
3,23.0,female,Bachelor,79753.0,0,RENT,35000.0,MEDICAL,15.23,0.44,2.0,675,No,1
4,24.0,male,Master,66135.0,1,RENT,35000.0,MEDICAL,14.27,0.53,4.0,586,No,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44995,27.0,male,Associate,47971.0,6,RENT,15000.0,MEDICAL,15.66,0.31,3.0,645,No,1
44996,37.0,female,Associate,65800.0,17,RENT,9000.0,HOMEIMPROVEMENT,14.07,0.14,11.0,621,No,1
44997,33.0,male,Associate,56942.0,7,RENT,2771.0,DEBTCONSOLIDATION,10.02,0.05,10.0,668,No,1
44998,29.0,male,Bachelor,33164.0,4,RENT,12000.0,EDUCATION,13.23,0.36,6.0,604,No,1
44999,24.0,male,High School,51609.0,1,RENT,6665.0,DEBTCONSOLIDATION,17.05,0.13,3.0,628,No,1

3. Z tej samej ramki danych wyświetl dane wykorzystując filtry oparte o mapowanie:
* a) tylko kobiety z wykształceniem 'Master' oraz 'Bachelor' i pożyczkami pomiędzy 50000 a 70000,
* b) wszyscy mężczyźni z wykształceniem innym niż 'Master' oraz będący właścicielem lokalu (kolumna person_home_ownership = OWN),
* c) wszystkie osoby z wartością `loan_percent_income` w przedziale od 0.4 do 0.6,
* d) wszystkie wartości pożyczek, których kwota jest wielokrotnością liczby 10000.

In [89]:
#a)
print("Max loan amount:", df['loan_amount'].max())
df[((df['loan_amount'] > 5_000) & (df['loan_amount'] < 7_000)) & (df['person_gender'] == 'female') & (df['person_education'].isin([ "Master", "Bachelor"]))]

Max loan amount: 35000.0

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amount,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
715,24.0,female,Bachelor,25826.0,4,OTHER,6000.0,PERSONAL,12.21,0.23,2.0,655,No,0
731,26.0,female,Bachelor,26792.0,4,OWN,5200.0,EDUCATION,12.42,0.19,3.0,674,No,0
799,25.0,female,Bachelor,27570.0,0,MORTGAGE,5875.0,EDUCATION,6.62,0.21,2.0,680,No,1
915,25.0,female,Bachelor,29498.0,6,MORTGAGE,6000.0,MEDICAL,14.59,0.20,2.0,664,No,1
950,25.0,female,Bachelor,29750.0,0,MORTGAGE,5800.0,DEBTCONSOLIDATION,5.99,0.19,3.0,639,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44780,25.0,female,Bachelor,71016.0,5,RENT,5578.0,MEDICAL,14.36,0.08,4.0,672,No,1
44814,33.0,female,Bachelor,44496.0,12,RENT,5610.0,HOMEIMPROVEMENT,11.98,0.13,7.0,687,No,1
44888,23.0,female,Bachelor,41805.0,0,RENT,6497.0,DEBTCONSOLIDATION,13.23,0.16,4.0,635,No,1
44901,25.0,female,Bachelor,24049.0,0,RENT,5937.0,HOMEIMPROVEMENT,12.38,0.25,3.0,675,No,1
44963,26.0,female,Bachelor,42960.0,5,RENT,6380.0,MEDICAL,15.95,0.15,6.0,686,No,1

In [90]:
#b)wszyscy mężczyźni z wykształceniem innym niż 'Master' oraz będący właścicielem lokalu (kolumna person_home_ownership = OWN),
df.query("person_education != 'Master' and person_gender == 'male' and person_home_ownership == 'OWN'")

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amount,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
27,23.0,male,High School,14293.0,0,OWN,1400.0,PERSONAL,9.32,0.10,3.0,607,No,0
30,21.0,male,High School,14858.0,0,OWN,2000.0,MEDICAL,11.12,0.13,3.0,589,No,1
35,21.0,male,Associate,15150.0,0,OWN,2500.0,EDUCATION,7.51,0.17,4.0,600,No,1
43,23.0,male,High School,361547.0,0,OWN,24250.0,EDUCATION,19.41,0.07,2.0,637,Yes,0
57,23.0,male,Bachelor,333399.0,1,OWN,35000.0,PERSONAL,11.01,0.10,4.0,609,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44353,25.0,male,High School,18772.0,2,OWN,4468.0,VENTURE,11.99,0.24,4.0,658,No,1
44391,26.0,male,Associate,15288.0,2,OWN,2690.0,EDUCATION,10.96,0.18,4.0,649,No,1
44543,30.0,male,High School,24052.0,8,OWN,7000.0,HOMEIMPROVEMENT,15.78,0.29,5.0,590,No,1
44683,23.0,male,Associate,23346.0,2,OWN,4027.0,VENTURE,15.01,0.17,4.0,646,No,1
44825,22.0,male,High School,22538.0,1,OWN,4913.0,EDUCATION,13.68,0.22,5.0,637,No,1

In [91]:
#c) wszystkie osoby z wartością `loan_percent_income` w przedziale od 0.4 do 0.6,
df.query("loan_percent_income >= 0.4 and loan_percent_income <= 0.6")

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amount,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
0,22.0,female,Master,71948.0,0,RENT,35000.0,PERSONAL,16.02,0.49,3.0,561,No,1
2,25.0,female,High School,12438.0,3,MORTGAGE,5500.0,MEDICAL,12.87,0.44,3.0,635,No,1
3,23.0,female,Bachelor,79753.0,0,RENT,35000.0,MEDICAL,15.23,0.44,2.0,675,No,1
4,24.0,male,Master,66135.0,1,RENT,35000.0,MEDICAL,14.27,0.53,4.0,586,No,1
22,22.0,female,Master,79255.0,0,RENT,34000.0,EDUCATION,17.58,0.43,4.0,691,No,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44903,25.0,male,Associate,43219.0,1,RENT,22807.0,MEDICAL,12.67,0.53,5.0,668,No,1
44940,29.0,male,High School,30046.0,7,RENT,12092.0,PERSONAL,11.79,0.40,7.0,535,No,1
44942,27.0,male,Master,48432.0,8,RENT,20223.0,VENTURE,6.83,0.42,8.0,650,No,1
44966,26.0,female,Bachelor,36844.0,0,RENT,16000.0,DEBTCONSOLIDATION,12.00,0.43,5.0,620,No,1
44986,34.0,male,Bachelor,41876.0,14,RENT,19594.0,DEBTCONSOLIDATION,12.03,0.47,8.0,707,No,1

In [92]:
#d) wszystkie wartości pożyczek, których kwota jest wielokrotnością liczby 10000.
df.query("loan_amount % 10000 == 0")

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amount,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
15,23.0,female,Master,600891.0,5,MORTGAGE,30000.0,DEBTCONSOLIDATION,10.65,0.05,3.0,670,Yes,0
36,22.0,female,Bachelor,58868.0,0,RENT,30000.0,EDUCATION,18.39,0.51,2.0,606,No,1
37,24.0,male,High School,78026.0,3,RENT,30000.0,DEBTCONSOLIDATION,14.54,0.38,3.0,582,No,1
38,25.0,male,Bachelor,90785.0,4,RENT,30000.0,HOMEIMPROVEMENT,16.89,0.33,4.0,649,No,1
39,23.0,female,High School,86811.0,0,RENT,30000.0,DEBTCONSOLIDATION,11.01,0.35,4.0,602,No,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44910,29.0,male,Bachelor,70997.0,6,RENT,20000.0,PERSONAL,13.28,0.28,5.0,676,No,1
44944,26.0,male,Associate,97590.0,7,RENT,30000.0,DEBTCONSOLIDATION,9.45,0.31,3.0,666,No,1
44953,36.0,male,Master,71544.0,13,RENT,10000.0,EDUCATION,10.85,0.14,15.0,576,No,1
44962,23.0,male,Associate,89930.0,0,MORTGAGE,10000.0,VENTURE,9.34,0.11,2.0,657,No,1
44984,24.0,female,High School,75941.0,1,RENT,20000.0,MEDICAL,14.85,0.26,4.0,592,No,1